name: PR CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: macos-latest
    
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5
    
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install corepack
        run: corepack enable && corepack prepare yarn@4.6.0 --activate
    
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Run format
        run: yarn format

      - name: Run lint
        run: yarn lint
    
      - name: Run tests
        run: yarn test
    
      - name: Build project
        run: yarn build